packages:
  - 'rulebook-checkstyle'
  - 'rulebook-codenarc'
  - 'rulebook-ktlint'
  - 'rulebook-cppcheck'
  - 'rulebook-pylint'
  - 'rulebook-eslint'
  - 'rulebook-typescript-eslint'
  - 'rulebook-cli'
  - 'codecheck'
  - 'testing'
  - 'stress-test'
  - 'sample'
  - 'sample-configured'
