version: 2.1

orbs:
  codecov: codecov/codecov@5.4.3

executors:
  multiplatform:
    docker:
      - image: hanggrian/cimg-multiplatform:openjdk21.0-python3.14-node
  renovate:
    docker:
      - image: renovate/renovate:latest

jobs:
  setup-workspace:
    executor: multiplatform
    steps:
      - checkout
      - run: ./gradlew dependencies --no-daemon
      - run: uv sync
      - run: pnpm i
      - persist_to_workspace:
          root: .
          paths: [.]
  run-lint:
    executor: multiplatform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check JVM
          command: ./gradlew checkstyleMain codenarcMain codenarcScript ktlintCheck --no-daemon
      - run:
          name: Check Python
          command: |
            uv run pylint rulebook-pylint/ --ignore-paths=rulebook-pylint/tests/resources/
            uv run pylint rulebook-cppcheck/
            uv run pylint sample/python/
            uv run pylint --rcfile=sample-configured/custom_pylintrc sample-configured/python/
      - run:
          name: Check C/C++
          command: |
            uv run cppcheck \
              --enable=performance,portability,style,warning \
              --addon=addon.json \
              sample/c/*.c \
              sample/cpp/*.cpp
            uv run cppcheck \
              --enable=performance,portability,style,warning \
              --addon=sample-configured/custom_addon.json \
              sample-configured/c/*.c \
              sample-configured/cpp/*.cpp
      - run:
          name: Check JS/TS
          command: |
            pnpm -r build
            pnpm lint
            pnpm lint2
  upload-coverage:
    executor: multiplatform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Report JVM
          command: ./gradlew koverXmlReport --no-daemon
      - run:
          name: Report Python
          command: |
            uv run pytest rulebook-cppcheck/ --cov=rulebook-cppcheck
            uv run pytest rulebook-pylint/ --cov=rulebook-pylint --cov-append
            uv run coverage xml
      - run:
          name: Report JS/TS
          command: |
            pnpm -r test
            pnpm -r coverage
      - codecov/upload
  activate-renovatebot:
    executor: renovate
    steps:
      - run: renovate

workflows:
  code-analysis:
    jobs:
      - setup-workspace
      - run-lint:
          requires: [setup-workspace]
      - upload-coverage:
          requires: [setup-workspace]
      - activate-renovatebot
