name: code-analysis

on:
  push:
  pull_request:

env:
  GRADLE_USER_HOME: ${{ github.workspace }}/.gradle/
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-workspace

      - name: Check JVM
        run: ./gradlew checkstyleMain codenarcMain codenarcScript ktlintCheck

      - name: Check Python
        run: |
          uv run pylint rulebook-pylint/ --ignore-paths=rulebook-pylint/tests/resources/
          uv run pylint rulebook-cppcheck/
          uv run pylint sample/python/
          uv run pylint --rcfile=sample-configured/custom_pylintrc sample-configured/python/

      - name: Check C/C++
        run: |
          uv run cppcheck \
            --check-level=exhaustive \
            --enable=performance,portability,style,warning \
            --addon=addon.json \
            rulebook-cli/src/*.cpp \
            rulebook-cli/src/*.hpp
          uv run cppcheck \
            --enable=performance,portability,style,warning \
            --addon=addon.json \
            sample/c/*.c \
            sample/cpp/*.cpp
          uv run cppcheck \
            --enable=performance,portability,style,warning \
            --addon=sample-configured/custom_addon.json \
            sample-configured/c/*.c \
            sample-configured/cpp/*.cpp

      - name: Check JS/TS
        run: |
          pnpm -r build
          pnpm lint
          pnpm lint2

  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-workspace

      - name: Report JVM
        run: ./gradlew koverXmlReport

      - name: Report Python
        run: |
          uv run pytest rulebook-cppcheck/ --cov=rulebook-cppcheck
          uv run pytest rulebook-pylint/ --cov=rulebook-pylint --cov-append
          uv run coverage xml

      - name: Report JS/TS
        run: |
          pnpm -r test
          pnpm -r coverage

      - uses: codecov/codecov-action@v5
        if: github.ref == 'refs/heads/main'
